package zprng

import org.bouncycastle.crypto.engines.ChaCha7539Engine
import org.bouncycastle.crypto.params.KeyParameter
import org.bouncycastle.crypto.params.ParametersWithIV
import zio.Chunk

import java.nio.ByteBuffer
import java.nio.ByteOrder

/** Pure cryptographic core using Bouncy Castle's ChaCha7539Engine.
  */
object ChaChaCore:

  /** Generates a chunk of random bytes based on the provided state.
    *
    * @param state
    *   The current RNG state.
    * @param numBytes
    *   The number of bytes to generate.
    * @return
    *   A tuple containing the generated bytes and the next RNG state.
    */
  def generateBytes(state: RNGState, numBytes: Int): (Chunk[Byte], RNGState) =
    require(state.key.size == RNGState.KeySize, s"Key must be ${RNGState.KeySize} bytes")
    require(state.nonce.size == RNGState.NonceSize, s"Nonce must be ${RNGState.NonceSize} bytes")
    require(numBytes > 0, "numBytes must be positive")
    require(state.counter >= 0, "Counter must be non-negative")

    val blocksNeeded = (numBytes + 63) / 64
    require(
      state.counter.toLong + blocksNeeded <= Int.MaxValue,
      "Counter overflow: too many bytes requested or reseed required"
    )

    val engine = new ChaCha7539Engine()
    val params = new ParametersWithIV(
      new KeyParameter(state.key.toArray),
      state.nonce.toArray
    )
    engine.init(true, params)

    // Set the counter. ChaCha7539 uses a 32-bit counter.
    // We need to skip to the correct block.
    // Each block is 64 bytes.
    // Bouncy Castle's ChaChaEngine.skip(long) skips bytes.
    if (state.counter != 0) {
      engine.skip(state.counter.toLong * 64)
    }

    val out = new Array[Byte](numBytes)
    engine.processBytes(new Array[Byte](numBytes), 0, numBytes, out, 0)

    val nextState = state.copy(counter = state.counter + (numBytes + 63) / 64)
    (Chunk.fromArray(out), nextState)

  /** Derives a new key from a parent key and a stream ID using SHA-256.
    */
  def deriveKey(parentKey: Chunk[Byte], streamId: Chunk[Byte]): Chunk[Byte] =
    val digest = java.security.MessageDigest.getInstance("SHA-256")
    digest.update("zprng:split:".getBytes("UTF-8"))
    digest.update(parentKey.toArray)
    digest.update(streamId.toArray)
    Chunk.fromArray(digest.digest())

  /** Mixes old key with entropy to produce a new key using SHA-256.
    */
  def mixEntropy(oldKey: Chunk[Byte], entropy: Chunk[Byte]): Chunk[Byte] =
    val digest = java.security.MessageDigest.getInstance("SHA-256")
    digest.update("zprng:reseed:".getBytes("UTF-8"))
    digest.update(oldKey.toArray)
    digest.update(entropy.toArray)
    Chunk.fromArray(digest.digest())
