version = "3.7.13"
runner.dialect = scala3
maxColumn = 100
align.preset = more
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
rewrite.rules = [RedundantParens, SortModifiers]
docstrings.style = SpaceAsterisk
lineEndings = unix
