---
sudo: required

env:
- RPRNG_ACTOR_COUNT=4

language: scala

services:
  - docker

scala:
    - 2.11.8
jdk:
  - oraclejdk8

# after main build is completed , build the docker container

script:
  - sbt ++$TRAVIS_SCALA_VERSION test assembly
