---
sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

env:
- RPRNG_ACTOR_COUNT=2

language: scala

scala:
    - 2.13.1
jdk:
  - openjdk11

script:
  - sbt ++$TRAVIS_SCALA_VERSION -Djava.security.egd=file:/dev/./urandom test assembly
